spring.datasource.url=jdbc:mysql://localhost:3306/backend?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=**
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.address=0.0.0.0
server.port=8080

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.database=0
spring.cache.type=redis
spring.cache.redis.time-to-live=600000
spring.cache.redis.cache-null-values=false

aliyun.oss.endpoint=oss-cn-wuhan-lr.aliyuncs.com
aliyun.oss.accessKeyId=LTAI5tJgyv4LvQ9HbXS69i5o
aliyun.oss.accessKeySecret=**
aliyun.oss.bucketName=microlesson-files
aliyun.oss.domain=https://microlesson-files.oss-cn-wuhan-lr.aliyuncs.com

spring.mail.host=smtp.qq.com
spring.mail.username=1152974119@qq.com
spring.mail.password=qrzmqeiwakuebaae
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

dashscope.api.key=**

did.api.key=**

# ai-engine gateway
ai.engine.base-url=http://127.0.0.1:8100
